theme: jekyll-theme-hacker
show_downloads: false
github:
  zip_url: https://github.com/imercury13/ya360/zipball/main
  tar_url: https://github.com/imercury13/ya360/tarball/main
plugins:
  - jekyll-feed
feed:
  path: "/news/feed.xml"
  categories:
    - news
