theme: jekyll-theme-slate
show_downloads: true
github:
  zip_url: https://github.com/imercury13/ya360/zipball/main
  tar_url: https://github.com/imercury13/ya360/tarball/main
  url: https://imercury13.github.io/ya360/
